---
title: "Práctica AE"
author: "Antonio Galián Gálvez"
date: "2024-10-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(encoding = "UTF-8")
```

# 0. Cargamos los datos y eliminamos la columna train
```{r}
# Cargamos los datos con separador de tabulador
datos <- read.delim("prostate.data.txt", header = TRUE, sep = "\t")

# Eliminamos la columna train
datos <- datos[, -ncol(datos)]
```

# 1. Exploración de datos
```{r}
# Vemos las variables que hay
ncol(datos)

# Eliminamos la columna id
datos <- datos[, -1]

# Comprobamos si hay NA
sum(is.na(datos))
# Como no hay NA, no hay que hacer ninguna limpieza

# Vemos la estructura de los datos
dim(datos)
names(datos)
str(datos)
summary(datos)
```

- Hay 10 variables, 9 si quitamos el id del paciente
- Las variables son numéricas

# 2

```{r}

attach(datos)

datos$svi <- as.factor(datos$svi)

datos$gleason <- as.factor(datos$gleason)

datos$age <- as.factor(datos$age)



str(datos)
```
#3
```{r}
a <- datos[datos$gleason == "7", ]

b <- a[a$svi == "0", ]

num.a <- dim(a)[1]

num.b <- dim(b)[1]

porcentaje.ab <- num.b / (num.a) * 100

c <- datos[datos$svi == "0", ]

d <- c[c$gleason == "7", ]

num.c <- dim(c)[1]

num.d <- dim(d)[1]

porcentaje.cd <- num.d / (num.c) * 100


tabla <- table(svi, gleason)

addmargins(prop.table(tabla,1),2)*100
addmargins(prop.table(tabla,2),1)*100

```

#4

```{r}
recta <- lm(lpsa ~ lcavol)

summary(recta)

plot(lcavol, lpsa)
abline(recta, col = "red")

confint(recta, level = 0.95)

r1 <- residuals(recta)
sqrt(sum(r1^2) / (dim(datos)[1] - 2)) # RSE


```

#5

```{r}

library(corrplot)

datos

corrplot(cor(datos[,c(-3,-5,-7)]),type="upper",tl.cex=0.5)

mul <-

```


